export const PHASE3_MASTER_FROM_P1 = 16;
export const PHASE3_MASTER_FROM_P2 = 16;
export const PHASE4_MASTER_FROM_P3_MASTER = 16;
export const PHASE4_AMATEUR_FROM_P3_AMATEUR = 8;
export const PHASE4_AMATEUR_WILDCARD_FROM_P3_AMATEUR = 2;
export const PHASE4_AMATEUR_TOTAL_PLAYERS = 24;
export const PHASE4_AMATEUR_FROM_P3_MASTER =
	PHASE4_AMATEUR_TOTAL_PLAYERS -
	PHASE4_AMATEUR_FROM_P3_AMATEUR -
	PHASE4_AMATEUR_WILDCARD_FROM_P3_AMATEUR;